export enum QUERY_TAG {
  PROFILE = "PROFILE",
  CATEGORIES = "CATEGORIES",
  ANALYTICS = "ANALYTICS",
  EXPENSES = "EXPENSES",
  TOTAL_EXPENSE = "TOTAL_EXPENSE",
  FINANCIAL_TIPS = "FINANCIAL_TIPS",
}
