export const TEXT = {
  appName: "Finman",
  login: "Đăng nhập",
  register: "Đăng ký",
  createAccount: "Tạo tài khoản",
  logout: "Đăng xuất",
  username: "Tên đăng nhập",
  password: "Mật khẩu",
  oldPassword: "Mật khẩu cũ",
  newPassword: "Mật khẩu mới",
  confirmPassword: "Nhập lại mật khẩu",
  confirmNewPassword: "Nhập lại mật khẩu mới",
  forgotPassword: "Quên mật khẩu",
  theme: "Nền",
  language: "Ngôn ngữ",
  home: "Trang chủ",
  analytics: "Phân tích",
  categories: "Phân loại",
  category: "Danh mục",
  expense: "Chi tiêu",
  noExpenses: "Không có chi tiêu",
  information: "Thông tin",
  description: "Mô tả",
  time: "Thời gian",
  amount: "Số tiền",
  chatbot: "Tư vấn tài chính",
  profile: "Hồ sơ",
  personal: "Cá nhân",
  advanceSettings: "Cài đặt nâng cao",
  name: "Tên",
  fullname: "Họ và tên",
  email: "Email",
  sex: "Giới tính",
  male: "Nam",
  female: "Nữ",
  other: "Khác",
  birthday: "Ngày sinh",
  phoneNumber: "Số điện thoại",
  address: "Địa chỉ",
  categoryName: "Tên danh mục",
  image: "Hình ảnh",
  pressToUpload: "Nhấn để tải lên",
  url: "Đường dẫn",
  exportReport: "Xuất báo cáo",
  export: "Xuất",
  exportHistory: "Báo cáo đã xuất",
  viewExportedReports: "Xem báo cáo đã xuất",
  startDate: "Ngày bắt đầu",
  endDate: "Ngày kết thúc",
  transactionHistory: "Lịch sử giao dịch",
  financialTips: "Mẹo quản lý tài chính",
  author: "Tác giả",
  hello: "Xin chào",
  history: "Lịch sử",
  balance: "Số dư",
  scanReceipt: "Scan hóa đơn",
  expenseType: "Loại chi tiêu",
  fileType: "Kiểu file",
  income: "Tiền vào",
  outcome: "Tiền ra",
  spent: "Đã chi tiêu",
  earned: "Đã nhận",
  link: "Liên kết",
  limit: "Hạn mức",
  almostLimit: "Sắp chạm mức chi tiêu",
  todayHint: "Gợi ý hôm nay",
  detail: "Chi tiết",
  actions: "Thao tác",
  showMore: "Xem thêm",
  showLess: "Thu gọn",
  yes: "Có",
  no: "Không",
  none: "Không",
  empty: "Trống",
  ok: "OK",
  cancel: "Hủy",
  close: "Đóng",
  reset: "Đặt lại",
  create: "Tạo",
  add: "Thêm",
  update: "Cập nhật",
  delete: "Xóa",
  errorOccurred: "Có lỗi xảy ra",
  networkError: "Lỗi mạng",
  imageTooLarge: "Hình ảnh quá lớn",
  startDateBeforeEndDate: "Ngày bắt đầu phải trước ngày kết thúc",
  pleaseConfirmPassword: "Hãy nhập lại mật khẩu",
  passwordDoNotMatch: "Mật khẩu không trùng khớp",
  sessionExpired: "Phiên đăng nhập hết hạn, vui lòng đăng nhập lại",
  cantIdentifyReceipt: "Không thể nhận diện hóa đơn, hãy quét lại",
};

export const SUMMARY = {
  invalid: (field: string) => `${field} không hợp lệ`,
  create: (field: string) => `Tạo ${field.toLocaleLowerCase()}`,
  add: (field: string) => `Thêm ${field.toLocaleLowerCase()}`,
  edit: (field: string) => `Chỉnh sửa ${field.toLocaleLowerCase()}`,
  update: (field: string) => `Cập nhật ${field.toLocaleLowerCase()}`,
  change: (field: string) => `Đổi ${field.toLocaleLowerCase()}`,
  delete: (field: string) => `Xóa ${field.toLocaleLowerCase()}`,
  enter: (field: string) => `Nhập ${field.toLocaleLowerCase()}`,
  select: (field: string) => `Chọn ${field.toLocaleLowerCase()}`,
  pleaseEnter: (field: string) => `Hãy nhập ${field.toLocaleLowerCase()}`,
  pleaseSelect: (field: string) => `Hãy chọn ${field.toLocaleLowerCase()}`,
  confirm: (action: string) =>
    `Bạn có chắc chắn muốn ${action.toLocaleLowerCase()} không?`,
  confirmDelete: (field: string) =>
    `Bạn có chắc chắn muốn xóa ${field.toLocaleLowerCase()} này không?`,
  successfully: (action: string) => `${action} thành công`,
  minLimit: (value: number, currency: string) =>
    `Hạn mức tối thiểu là ${value}${currency}`,
  minLengthPassword: (value: number) =>
    `Độ dài mật khẩu tối thiểu là ${value} ký tự`,
};
