export const TEXT = {
  appName: "Finman",
  login: "Đăng nhập",
  register: "Đăng ký",
  home: "Trang chủ",
  analytics: "Phân tích",
  categories: "Phân loại",
  chatbot: "Tư vấn tài chính",
  profile: "Hồ sơ",
  transactionHistory: "Lịch sử giao dịch",
  financeTips: "Mẹo quản lý tài chính",
  hello: "Xin chào",
  history: "Lịch sử",
  balance: "Số dư",
  scanBill: "Scan hóa đơn",
  addExpense: "Thêm chi tiêu",
  link: "Liên kết",
  almostLimit: "Sắp chạm mức chi tiêu",
  todayHint: "Gợi ý hôm nay",
  detail: "Chi tiết",
  showMore: "Xem thêm",
  showLess: "Thu gọn",
};
